console.log("BunPress CLI Demo");
console.log("\nCommand: help");
console.log("-------------------");
console.log("BunPress - A modern static site generator built with Bun\n");
console.log("Usage:");
console.log("  bunpress init [dir]    Initialize a new BunPress project in the specified directory");
console.log("                         or current directory if not specified");
console.log("  bunpress dev           Start the development server (default command)");
console.log("  bunpress build         Build the site for production");
console.log("  bunpress help          Display this help message");
console.log("  bunpress version       Display version information\n");
console.log("Options:");
console.log("  -h, --help             Display help information");
console.log("  -v, --version          Display version information\n");
console.log("Examples:");
console.log("  bunpress init my-site  Create a new project in the my-site directory");
console.log("  bunpress dev           Start the development server");
console.log("  bunpress build         Build the site for production\n");
console.log("Documentation:");
console.log("  https://github.com/bunpress/bunpress");
console.log("\n\nCommand: build");
console.log("-------------------");
console.log("✨ Build completed successfully!\n");
console.log("📊 Stats: 24 files (128.45 KB)");
console.log("📂 Output: /home/user/project/dist\n");
console.log("\n\nCommand: dev");
console.log("-------------------");
console.log("🚀 Starting development server...\n");
console.log("🌐 Server running at:");
console.log("  ➜ Local:   http://localhost:3000");
console.log("  ➜ Network: http://192.168.1.100:3000\n");
console.log("🔥 Hot Module Replacement enabled\n");
console.log("👀 Watching for changes..."); 