name: BunPress CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
      
      - name: Type check
        run: bun lint
        
      - name: Run tests
        run: bun test
      
      - name: Build project
        run: bun run build
      
      - name: Create test project
        run: |
          mkdir -p test-project
          cd test-project
          ../bin/bunpress.js init
          ../bin/bunpress.js build

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
      
      - name: Run TypeScript type check
        run: bun lint:strict 